### ISSUE TITLE
Overwatch is started without any arguments

### ISSUE THREAD

**Issue by sorashi** [dafzor/bnetlauncher#2]
I followed your instructions, but haven't succeded in starting Overwatch with Steam overlay. The app always ends on [this line](https://github.com/dafzor/bnetlauncher/blob/master/bnetlauncher/Program.cs#L227)
> Failed to obtain game parameters. Game should start but steam overlay won't be attached to it.

I made a quick test
```csharp
Process.Start(owLauncher);
var start = DateTime.Now;
Process owp = null;
while ((DateTime.Now - start).Seconds < 30) {
    owp = Process.GetProcesses().FirstOrDefault(x => x.ProcessName == "Overwatch");
    if (owp != null) break;
    Thread.Sleep(500);
}
if (owp == null) {
    Console.WriteLine("Overwatch process search timeout");
    return;
}
Console.WriteLine($"Info found:\nFileName: {owp.StartInfo.FileName}\nArguments: {owp.StartInfo.Arguments}");
```
Output (after I manually start Overwatch in Battle.Net):
```
ProcessInfo found:
FileName:
Arguments:
```
`FileName` and `Arguments` are always empty. It may be a recent change in Battle.Net/Overwatch.

**Comment by sorashi** [comment]
Just saw your commits you made 3 days ago. It seems you already know about it. I tried reinstalling the Battle.Net client, it didn't help. I also tried cloning your code, building it and using it instead (to reflect your recent changes).

**Comment by dafzor** [comment]
I have Overwatch and it's currently working with bnetlauncher when i launch it, with or without battle.net client running.

As for your test, 

*"If you did not use the Start method to start a process, the StartInfo property does not reflect the parameters used to start the process. For example, if you use GetProcesses to get an array of processes running on the computer, the StartInfo property of each Process does not contain the original file name or arguments used to start the process."* in [Process.StartInfo documentation](https://msdn.microsoft.com/en-us/library/system.diagnostics.process.startinfo(v=vs.110).aspx)

That is the reason why I use System.Management API to retrieve the StartInfo, should have probably added a comment about it.

As remarked in the GetProcessStartInfoById it does sometime fail which is why I have retry code but I have never had it return empty values, so at least locally I can't seem to reproduce the issue, I could try fixing it by adding a check for empty and retry but would prefer to try and figure out what's going on before I "fix it".

**Comment by dafzor** [comment]
Could you enable the log file and send it over?

**Comment by sorashi** [comment]
The log: http://pastebin.com/7XFDtvhU

**Comment by sorashi** [comment]
I'll try debugging and finding the cause. I know there isn't much you can do about it - seems I'm the only one having the issue.

**Comment by sorashi** [comment]
So I debugged it and found the problem. The `searcher.Get()` was returning an empty collection, so it wasn't throwing any exception. It just skipped the `foreach` loop and continued trying.
![Debugging](https://a.desu.sh/adeksd.gif)

I thought - maybe it was a permission problem. So I tried setting `bnetlauncher.exe` to always run as an administrator and it works now.

I can see though, that you have `<requestedExecutionLevel level="asInvoker" uiAccess="false" />` in `app.manifest`, so it should require the permission automatically.

So I assume my OS is acting weird and it is not your app's problem.

Thanks for this great app and good luck with future development. And sorry that I bothered you with this without even trying such a basic thing like running it as an administrator.

**Comment by dafzor** [comment]
It's weird, on my system I don't run it as admin and returns proper results, did you change/disable the UAC settings or run the game as admin by any chance?

**Comment by sorashi** [comment]
Yes, my UAC is set to *never notify* and I have set Overwatch to run as an administrator. That was exactly the problem.

**Comment by dafzor** [comment]
I'll try and see if there's any way to fix it or at the very least provide some warnings about it, thanks for all the testing and debugging.
